behaviors:
  SoccerTwos:
    trainer_type: poca
    hyperparameters:
      batch_size: 6000
      buffer_size: 60000
      learning_rate: 0.0001
      beta: 0.001
      epsilon: 0.27
      lambd: 0.945
      num_epoch: 8
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple 
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 1000000000
    time_horizon: 2048
    summary_freq: 50000
    self_play:
      save_steps: 20000
      team_change: 160000
      swap_steps: 10000
      window: 20
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0